<?php 


if (function_exists('acf_add_local_field_group')) {

    acf_add_local_field_group(array(
    'key' => 'group_69445f2589f85',
    'title' => __('Quick links', 'modularity-quick-links'),
    'fields' => array(
        0 => array(
            'key' => 'field_69445f256a00a',
            'label' => __('Max items per row', 'modularity-quick-links'),
            'name' => 'max_items_per_row',
            'aria-label' => '',
            'type' => 'select',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '33',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                2 => __('Two', 'modularity-quick-links'),
                4 => __('Four', 'modularity-quick-links'),
                6 => __('Six', 'modularity-quick-links'),
                8 => __('Eight', 'modularity-quick-links'),
            ),
            'default_value' => 4,
            'return_format' => 'value',
            'multiple' => 0,
            'allow_custom' => 0,
            'placeholder' => '',
            'search_placeholder' => '',
            'allow_null' => 0,
            'allow_in_bindings' => 0,
            'ui' => 0,
            'ajax' => 0,
            'create_options' => 0,
            'save_options' => 0,
        ),
        1 => array(
            'key' => 'field_69445fc16a00b',
            'label' => __('Icons?', 'modularity-quick-links'),
            'name' => 'use_icons',
            'aria-label' => '',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '33',
                'class' => '',
                'id' => '',
            ),
            'message' => '',
            'default_value' => 0,
            'allow_in_bindings' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
            'ui' => 1,
        ),
        2 => array(
            'key' => 'field_694460036a00c',
            'label' => __('Short description?', 'modularity-quick-links'),
            'name' => 'use_short_description',
            'aria-label' => '',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '34',
                'class' => '',
                'id' => '',
            ),
            'message' => '',
            'default_value' => 0,
            'allow_in_bindings' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
            'ui' => 1,
        ),
        3 => array(
            'key' => 'field_694460306a00d',
            'label' => __('Large icons?', 'modularity-quick-links'),
            'name' => 'large_icons',
            'aria-label' => '',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_69445fc16a00b',
                        'operator' => '==',
                        'value' => '1',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => '',
            'default_value' => 0,
            'allow_in_bindings' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
            'ui' => 1,
        ),
        4 => array(
            'key' => 'field_6957c3d4da403',
            'label' => __('Link gap', 'modularity-quick-links'),
            'name' => 'link_gap',
            'aria-label' => '',
            'type' => 'select',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                0 => __('0 - 1px (No gap - original border style)', 'modularity-quick-links'),
                1 => __('1 - 0.5rem', 'modularity-quick-links'),
                2 => __('2 - 1rem', 'modularity-quick-links'),
                3 => __('3 - 1.5rem', 'modularity-quick-links'),
                4 => __('4 - 2rem', 'modularity-quick-links'),
                5 => __('5 - 2.5rem', 'modularity-quick-links'),
                6 => __('6 - 3rem', 'modularity-quick-links'),
                7 => __('7 - 3.5rem', 'modularity-quick-links'),
                8 => __('8 - 4rem', 'modularity-quick-links'),
                9 => __('9 - 4.5rem', 'modularity-quick-links'),
                10 => __('10 - 5rem', 'modularity-quick-links'),
            ),
            'default_value' => 0,
            'return_format' => 'value',
            'multiple' => 0,
            'allow_custom' => 0,
            'placeholder' => '',
            'search_placeholder' => '',
            'allow_null' => 0,
            'allow_in_bindings' => 0,
            'ui' => 0,
            'ajax' => 0,
            'create_options' => 0,
            'save_options' => 0,
        ),
        5 => array(
            'key' => 'field_694460586a00e',
            'label' => __('Links', 'modularity-quick-links'),
            'name' => 'links',
            'aria-label' => '',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'acfe_repeater_stylised_button' => 0,
            'layout' => 'block',
            'pagination' => 0,
            'min' => 2,
            'max' => 0,
            'collapsed' => 'field_694460786a00f',
            'button_label' => __('Add link', 'modularity-quick-links'),
            'rows_per_page' => 20,
            'sub_fields' => array(
                0 => array(
                    'key' => 'field_694460876a010',
                    'label' => __('Icon', 'modularity-quick-links'),
                    'name' => 'icon',
                    'aria-label' => '',
                    'type' => 'icon',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => array(
                        0 => array(
                            0 => array(
                                'field' => 'field_69445fc16a00b',
                                'operator' => '==',
                                'value' => '1',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'allow_in_bindings' => 0,
                    'default_value' => '',
                    'placeholder' => '',
                    'parent_repeater' => 'field_694460586a00e',
                ),
                1 => array(
                    'key' => 'field_694460786a00f',
                    'label' => __('Title', 'modularity-quick-links'),
                    'name' => 'title',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => '',
                    'allow_in_bindings' => 0,
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'parent_repeater' => 'field_694460586a00e',
                ),
                2 => array(
                    'key' => 'field_694460cc6a012',
                    'label' => __('Link', 'modularity-quick-links'),
                    'name' => 'link',
                    'aria-label' => '',
                    'type' => 'link',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'return_format' => 'array',
                    'allow_in_bindings' => 0,
                    'parent_repeater' => 'field_694460586a00e',
                ),
                3 => array(
                    'key' => 'field_694460b46a011',
                    'label' => __('Description', 'modularity-quick-links'),
                    'name' => 'description',
                    'aria-label' => '',
                    'type' => 'textarea',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => array(
                        0 => array(
                            0 => array(
                                'field' => 'field_694460036a00c',
                                'operator' => '==',
                                'value' => '1',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'acfe_textarea_code' => 0,
                    'maxlength' => '',
                    'allow_in_bindings' => 0,
                    'rows' => 2,
                    'placeholder' => '',
                    'new_lines' => '',
                    'parent_repeater' => 'field_694460586a00e',
                ),
            ),
        ),
    ),
    'location' => array(
        0 => array(
            0 => array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'mod-quick-links',
            ),
        ),
        1 => array(
            0 => array(
                'param' => 'block',
                'operator' => '==',
                'value' => 'acf/quick-links',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'left',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
    'display_title' => '',
    'acfe_autosync' => array(
        0 => 'json',
    ),
    'acfe_form' => 0,
    'acfe_meta' => '',
    'acfe_note' => '',
));

}